DROP TABLE IF EXISTS T_USER; 
CREATE TABLE T_USER ( 
UID CHAR(32) NOT NULL,
USERNAME VARCHAR (50) NOT NULL, 
PASSWORD VARCHAR (50) NOT NULL, 
EMAIL VARCHAR (50) DEFAULT NULL, 
STATUS TINYINT (1) DEFAULT NULL, 
PRIMARY KEY (UID),
UNIQUE KEY USERNAME(USERNAME) 
) ENGINE=INNODB DEFAULT CHARSET=UTF8; 